### ISSUE TITLE
Checks to add to ACCESS-OM3 Payu driver

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/access-om3-configs#298]
We've discussed adding checks to the Payu driver to be run at setup to help ensure the configuration is valid. This issue is to list/discuss the checks we might want to include.

- [ ] Check that the naming of MOM outputs in `diag_table` is consistent with the `case_name` set in `nuopc_runconfig` - see ACCESS-NRI/access-om3-configs#296
- [ ] Check for consistency in physical constants - see ACCESS-NRI/access-om3-configs#256
- [ ] Check for consistency across parameters set in multiple places - see https://github.com/COSIMA/access-om3/issues/108
